# Generated by Django 3.0.2 on 2020-01-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='fullDesc',
            new_name='full_desc',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='smallDesc',
            new_name='small_desc',
        ),
    ]
